<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Handlers\" />
    <Folder Include="Ports\" />
    <Folder Include="Querys\" />
  </ItemGroup>

</Project>
